---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        {{- with .Values.vault }}
        vault.hashicorp.com/agent-inject: {{ .inject | quote }}
        vault.hashicorp.com/role: {{ .role | quote }}
        vault.hashicorp.com/agent-inject-secret-{{ .secretConfigFileName }}: {{ .secretConfigPath | quote }}
        # Environment variable export template
        vault.hashicorp.com/agent-inject-template-config: |
          {{ "{{" }}- with secret {{ .secretConfigPath | quote }} {{ "-}}" }}
            {{- range $key, $val := .envVar }}
            export {{ $key -}}={{ $val | quote }}
            {{- end}}
          {{ "{{-" }} end {{ "}}" }}
    spec:
      serviceAccountName: web
      containers:
        - name: web
          image: alpine:latest
          command:
            ['sh', '-c']
          args:
            ['source /vault/secret/{{ .secretConfigFileName }} && {{ .entryPoint }}']
          {{- end }}
          ports:
            - containerPort: 9090
